### ISSUE TITLE
touple doesn't work correctly on a complex redux store. 

### ISSUE THREAD

**Issue by martinrojas** [harryhope/hooked-on-redux#6]
As I have been trying to integrate hooked-on-redux in an existing project that contains multiple reducers there has been an issue that the getter and setter are working differently. 

To be able to retrieve the value correctly I have to include the name of the reducer. However, this breaks the second part of the touple. To get the correct behavior there has to be something like this:

```
	const [loading] = useHookedOnState('flamingo.loading', true);
	const [, loading] = useHookedOnState('loading', true);
```
This is not even a possible solution because if the default state is an `{}` then redux gets into an infinite loop.

**Comment by harryhope** [comment]
Hey @martinrojas 

I’m not sure I understand the problem you’re facing based on that description. Could you show me a code sample or codepen of this not working?

**Comment by martinrojas** [comment]
Created a sandbox that demonstrates the issue Hope this helps. 

https://codesandbox.io/s/hooked-on-redux-issue-with-complex-store-279jr

I was thinking that some sort of extra parameter on the hook would adress this.

**Comment by harryhope** [comment]
Alright thanks, that helps me understand the problem better.

From what I've seen, `combineReducers` abstracts out dispatches so that they don't have to be aware of the top level key but obviously when you are selecting state you need to be aware of the top level keys that it is adding.

I'm hesitant to add more parameters to `useHookedOnState` to solve this, because I think that would complicate the method signature too much.

I almost feel like the solution for this is to export our own `combineReducers` function that ensures that the hooked-on-redux reducer doesn't get dropped into a top level key. I'm leaning towards this since even the redux documentation hints that it's acceptable to create your own `combineReducers` function https://redux.js.org/api/combinereducers#tips

**Comment by martinrojas** [comment]
I can see the appeal of taking the route to create a new `combineReducers`, However, as I have been thinking about it from the point of view of a developer with an existing app I would be a lot more hesitant to change away from the "official" Redux one. Also, that seems to break the redux pattern and due to the flexibility afforded by these hooks, it would be a lot easier to have collisions with existing code that may have similar keys and their own reducers.

Also, I realize that this is only an issue for those with existing stores and to make the main method signature more complex doesn't make sense. What do you think about exporting a **"complex"** version of the hook? Having a `useComplexHookedOnState` can provide an option for those that want to adopt the new pattern incrementally in their project.
